
#端口号
server:
  port: 8081
  
#数据库链接设置
spring:
 datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subject?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password:
    hikari:                             ##  Hikari 连接池配置
        minimum-idle: 5                 ## 最小空闲连接数量
        idle-timeout: 180000            ## 空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 10           ## 连接池最大连接数，默认是10
        auto-commit: true               ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        pool-name: MyHikariCP           ## 连接池母子
        max-lifetime: 1800000           ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000       ## 数据库连接超时时间,默认30秒，即30000
        connection-test-query: SELECT 1


#整合Mybatis
mybatis:
  type-aliases-package: com.subject.model #  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml #  多层级目录  mapper-locations: classpath:mapper/**/**.xml
  
